apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: kube-ops
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-ops
  nfs:
    path: /data/jk/
    server: 10.140.0.2
